"""Synthetic e-waste recycler and benchmark generator.

Provenance Note:
All data generated by this module is purely SYNTHETIC for development,
simulation, and demonstration purposes under SIH PS 26229.
Provenance tag: 'source: synthetic'
"""

import datetime
import json
from pathlib import Path

GENERATOR_VERSION = "0.1.0"

SYNTHETIC_RECYCLERS = [
    {
        "recycler_id": "REC-SYNTH-001",
        "legal_name": "Maharashtra Green E-Solutions (Synthetic)",
        "cpcb_reg_no": "CPCB/SYNTH/EPR/2026/001",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "region": "MH_MUMBAI",
        "capacity_mt_per_month": 150.0,
        "accepted_categories": ["pcb_grade_a", "pcb_grade_b", "lithium_ion_battery"],
        "provenance": {
            "source": "synthetic",
            "generator_version": GENERATOR_VERSION,
            "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        },
    },
    {
        "recycler_id": "REC-SYNTH-002",
        "legal_name": "Pune Circular Resources Pvt Ltd (Synthetic)",
        "cpcb_reg_no": "CPCB/SYNTH/EPR/2026/002",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "region": "MH_PUNE",
        "capacity_mt_per_month": 220.0,
        "accepted_categories": ["crt_monitor", "flat_display", "mixed_e_waste"],
        "provenance": {
            "source": "synthetic",
            "generator_version": GENERATOR_VERSION,
            "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        },
    },
]


def export_synthetic_recyclers(output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(SYNTHETIC_RECYCLERS, f, indent=2)
    print(f"Exported {len(SYNTHETIC_RECYCLERS)} synthetic recyclers to {output_path}")


if __name__ == "__main__":
    dest = Path(__file__).parent / "synthetic_recyclers.json"
    export_synthetic_recyclers(dest)
